import type { Metadata } from "next";
import { Geist, Geist_Mono ,Inter, Jersey_10, Tiny5 } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Gamefont = Jersey_10({
  subsets: ["latin"],
  variable: "--font-game",
  weight: ["400"]
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
 })


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
 <ClerkProvider>
    <html lang="en" suppressHydrationWarning className="dark">
      <body
      suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable}
        ${Gamefont.variable} ${inter.variable}
        antialiased`}
      >
        <Provider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            {children}
          </TooltipProvider>
          <Toaster/>
        </Provider>
      </body>
    </html> 
    </ClerkProvider>
  );
}
